# Generated by Django 4.0.4 on 2022-05-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected'), ('Completed', 'Completed'), ('Completed', 'Completed'), ('Final approval from boss', 'Final approval from boss')], default='Processing', max_length=50),
        ),
    ]
